### ISSUE TITLE
Use of getPreventDefault() is deprecated

### ISSUE THREAD

**Issue by Bugsbane** [rydama/mailchimp-ajax-signup#4]
Hi there,

When I try to get this to work, using my Mailchimp url ( yes, I used http:// and added post-json ) it just hangs saying "Subscribing..." without ever completing.

The console gives the following error:

> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by Bugsbane** [comment]
Seems this is a known issue with jquery 1.10.2 as seen on the bug tracker [here](http://bugs.jquery.com/ticket/14282).

**Comment by rydama** [comment]
I've updated to jquery 1.11.3 to git rid of the message.

I tested and it works in chrome, firefox, and safari (mac).

If you're still having the issue. Can you provide more info. Which browser and version, and attach the html file you're using?

**Comment by Bugsbane** [comment]
Thanks! I'm a bit snowed under right now, but I'll give this a try as soon as I have a minute. I'm rather desperate for a way to redirect users who are already subscribed, and this looks like it might be the gateway to doing exactly that. Will report back later. Previously I tried with the current versions of both Chrome and Firefox (sorry to not remember exact version numbers)

**Comment by Bugsbane** [comment]
It's working great now! THANK YOU!

I only have one issue, which seems better put in a new ticket, so I'll do that now.
