### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token u" in Chrome Console

### ISSUE THREAD

**Issue by flaturtha** [rydama/mailchimp-ajax-signup#5]
I've received the error "Uncaught SyntaxError: Unexpected token u" on my site the last couple of days. Based on my research (specifically stackoverflow: http://stackoverflow.com/questions/13022178/uncaught-syntaxerror-unexpected-token-u-json), it seems to be connected to a JSON-p undefined error. Since ChimpBuddy and this Ajax-Mailchimp script are all I have using JSON-p on my site, I assume it's connected.

But I don't know enough to be sure; therefore I thought I'd pass it along as a possible issue. 

It has been working no problem for a couple weeks since I started using it. This error is new within a day or so.

**Comment by rydama** [comment]
I haven't seen that before. Can you point me to your signup form where this is happening?

**Comment by flaturtha** [comment]
The link to the page with the form is: http://554bc9f2f92ea112ef000002.governor-cow-56818.netlify.com/. I'm currently not up on my normal URL since I'm still developing and testing. But this shows the error under Chrome's Developer Tools/Console. Just click the "Click to reveal solution" then scroll to the bottom of the page for the form.

**Comment by rydama** [comment]
Hi Rich, I took a look. The error is happening as soon as the page is loaded. It's not yet getting to the mailchimp related code.

It looks like the problem is here... **store.get("storyMeta")** returns undefined:
```
var retrievedMetaString = store.get("storyMeta"); // this returns undefined
var retrievedMetaArray = JSON.parse(retrievedMetaString); // so, JSON.parse throws the unexpected token u error
```

The firefox debugger was a lot more helpful at pinpointing the problem.

You probably need to change it to something like:

```
var retrievedMetaString = store.get("storyMeta");
if (retrievedMetaString) {
    var retrievedMetaArray = JSON.parse(retrievedMetaString);
    document.getElementById("title").innerHTML = retrievedMetaArray[0];
    document.getElementById("author").innerHTML = retrievedMetaArray[1];
    document.getElementById("genre").innerHTML = retrievedMetaArray[2];
    document.getElementById("image").src = retrievedMetaArray[3];
    document.getElementById("excerpt").innerHTML = retrievedMetaArray[4];
    document.getElementById("kindle").href = retrievedMetaArray[5];
    document.getElementById("epub").href = retrievedMetaArray[6];
    document.getElementById("pdf").href = retrievedMetaArray[7];

    $(".download-title").html(retrievedMetaArray[0]);
}
```

Hope that helps

**Comment by flaturtha** [comment]
Ok. Good. I figured it was likely something on my end but couldn't figure
it out. Thanks for looking and finding that. I'll work through my code and
fix.

**Comment by flaturtha** [comment]
Yup. Your variation on my code work. SORRY about that. I'd overlooked that
bit of code also using JSON parse.

That's what I get for trying to write javascript/jquery without really
knowing what I'm doing!

Greatly appreciate the assist. Works fine now.

**Comment by rydama** [comment]
No worries. Glad you got it working!
