### ISSUE TITLE
Firefox: The resource at "..." was blocked because tracking protection is enabled.

### ISSUE THREAD

**Issue by dmxt** [rydama/mailchimp-ajax-signup#6]
**Error:**
```
The resource at "http://***.us11.list-manage.com/subscribe/post-json?u=1f044ac4924517fc1007369aa&id=1e643f77de&c=jQuery111304645108639459916_1443659611085&FNAME=test&EMAIL=test%40testd.com&_=1443659611086" was blocked because tracking protection is enabled.
```

[More information about this issue](https://support.mozilla.org/en-US/kb/tracking-protection-firefox)

Subscription works fine on Chrome and this issue occurs on Firefox. How do I resolve this issue?

**Comment by rydama** [comment]
Sorry, I don't think there is anything that can be done about it. Apparently mailchimp is on firefox's blocklist for tracking protection. It appears that "tracking protection" is some kind of advanced option in firefox and can only be turned on in the hidden advanced options screen. So, I doubt it is a widespread issue.

Note: this advanced "tracking protection" is not the same as the Privacy option for "do not track" as shown here:
![image](https://cloud.githubusercontent.com/assets/1431500/10248328/98ec8d2e-68d3-11e5-88a5-4db728321528.png)

This option seems fine and compatible with the mailchimp form.

**Comment by savolai** [comment]
(Sorry to comment on a closed issue.) Mailchimp signup popup is not showing for me on firefox either, citing the same error message. AFAIK I haven't enabled any advanced blocking but I may have forgotten about it. Do you know a way to verify what the firefox setting is and how to confirm?

**Comment by savolai** [comment]
Also chrome appears to do this sometimes.
